export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_CLEAR_INPUT_VALUE = 'FETCH_CLEAR_INPUT_VALUE';
export const FETCH_INPUT_VALUE = 'FETCH_INPUT_VALUE';
export const FETCH_SEARCH_BUTTON = 'FETCH_SEARCH_BUTTON';
export const FETCH_CLEAR_INPUT = 'FETCH_CLEAR_INPUT';