export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_CLEAR_INPUT_VALUE = 'FETCH_CLEAR_INPUT_VALUE';
export const FETCH_INPUT_VALUE = 'FETCH_INPUT_VALUE';
export const FETCH_SEARCH_BUTTON = 'FETCH_SEARCH_BUTTON';
export const FETCH_CLEAR_INPUT = 'FETCH_CLEAR_INPUT';

export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_CLICKED_SEARCH_ELEMENT = 'FETCH_CLICKED_SEARCH_ELEMENT';
export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';

export const FETCH_SUCCESS_ADD_TO_FAVORITE='FETCH_SUCCESS_ADD_TO_FAVORITE';
export const FETCH_SUCCESS_DELETE = 'FETCH_SUCCESS_DELETE';
export const FETCH_SELECT_ITEM ='FETCH_SELECT_ITEM';
